import sys
from pathlib import Path

try:
    from . import config
except ImportError:
    import config

try:
    import reapy_boost as rpr
    from reapy_boost import reascript_api as RPR
except ImportError:
    print("[render] ERROR: reapy_boost not installed")
    sys.exit(1)


def render_mix(output_dir: Path):
    """
    Renders ES VOX + EN M&E to FLAC.
    Filename is generated by Reaper using $project (e.g., s01e06.flac).
    """
    
    print(f"[render] Connecting to Reaper...")
    
    try:
        with rpr.inside_reaper():
            project = rpr.Project()
            
            project_name = project.name if hasattr(project, 'name') else 'Unsaved'
            print(f"[render] Active project: {project_name}")
            
            # Find tracks by name
            tracks = list(project.tracks)
            
            track_en_vox = None
            track_es_vox = None
            track_en_music = None
            track_es_music = None
            
            for track in tracks:
                if config.TRACK_EN_VOX in track.name:
                    track_en_vox = track
                elif config.TRACK_ES_VOX in track.name:
                    track_es_vox = track
                elif config.TRACK_EN_MUSIC in track.name:
                    track_en_music = track
                elif config.TRACK_ES_MUSIC in track.name:
                    track_es_music = track
            
            if not track_es_vox:
                print(f"[render] ERROR: Track '{config.TRACK_ES_VOX}' not found")
                sys.exit(1)
            
            if not track_en_music:
                print(f"[render] ERROR: Track '{config.TRACK_EN_MUSIC}' not found")
                sys.exit(1)
            
            print(f"[render] OK: Tracks found")
            print(f"[render]   - {track_es_vox.name}")
            print(f"[render]   - {track_en_music.name}")
            
            # Save original mute/solo state
            print(f"[render] Saving original track states...")
            original_states = {}
            for track in tracks:
                mute = RPR.GetMediaTrackInfo_Value(track.id, "B_MUTE")
                solo = RPR.GetMediaTrackInfo_Value(track.id, "I_SOLO")
                original_states[track.id] = {"mute": mute, "solo": solo}
            
            # Configure: only ES VOX and EN M&E
            print(f"[render] Configuring tracks for render...")
            print(f"[render]   Solo: {config.TRACK_ES_VOX} + {config.TRACK_EN_MUSIC}")
            print(f"[render]   Mute: Remaining tracks")
            
            for track in tracks:
                if track.id == track_es_vox.id or track.id == track_en_music.id:
                    # Enable these tracks
                    RPR.SetMediaTrackInfo_Value(track.id, "B_MUTE", 0)
                    RPR.SetMediaTrackInfo_Value(track.id, "I_SOLO", 1)
                else:
                    # Mute the rest
                    RPR.SetMediaTrackInfo_Value(track.id, "B_MUTE", 1)
                    RPR.SetMediaTrackInfo_Value(track.id, "I_SOLO", 0)
            
            # Configure render settings
            print(f"[render] Configuring render...")
            print(f"[render]   Output directory: {output_dir}")
            print(f"[render]   Format: {config.CODEC.upper()} {config.BIT_DEPTH}-bit {config.SAMPLE_RATE//1000} KHz")
            print(f"[render]   Filename: Configured in Reaper ($project)")
            
            # Set output directory
            RPR.GetSetProjectInfo_String(project.id, "RENDER_FILE", str(output_dir), True)
            
            # Update
            RPR.UpdateArrange()
            
            print(f"[render] Starting render...")
            print(f"[render] NOTE: Render preset must be configured for:")
            print(f"[render]   - Source: Master mix")
            print(f"[render]   - Bounds: Entire project")
            print(f"[render]   - Format: FLAC, 48000 Hz, 16 bit")
            print(f"[render]   - File name: $project (wildcard)")
            
            # Run render using most recent settings
            # Action 41824 = File: Render project, using the most recent render settings
            RPR.Main_OnCommand(41824, 0)
            
            # Wait a moment for render to start
            import time
            time.sleep(2)
            
            print(f"[render] Render started...")
            print(f"[render] Waiting for render to finish...")
            
            # Restore original state
            print(f"[render] Restoring original track states...")
            for track in tracks:
                if track.id in original_states:
                    RPR.SetMediaTrackInfo_Value(track.id, "B_MUTE", original_states[track.id]["mute"])
                    RPR.SetMediaTrackInfo_Value(track.id, "I_SOLO", original_states[track.id]["solo"])
            
            # Update
            RPR.UpdateArrange()
            
            # Calculate final filename
            project_basename = Path(project_name).stem if project_name != 'Unsaved' else 'output'
            final_file = output_dir / f"{project_basename}.{config.CODEC}"
            
            print(f"[render]")
            print(f"[render] OK: Render completed")
            print(f"[render] Expected file: {final_file}")
            
    except Exception as e:
        print(f"[render] ERROR: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"[render] Sherlock Audio Pipeline - Render Mix")
        print(f"[render]")
        print(f"[render] Renders {config.TRACK_ES_VOX} + {config.TRACK_EN_MUSIC} using Reaper's render settings.")
        print(f"[render] Filename is generated by Reaper using the $project wildcard.")
        print(f"[render]")
        print(f"[render] Usage:")
        print(f"[render]   python3 steps/reaper_render.py <output_directory>")
        print(f"[render]")
        print(f"[render] Example:")
        print(f"[render]   python3 steps/reaper_render.py '{config.OUTPUT_DIR}'")
        print(f"[render]")
        print(f"[render] If the project is named 's01e06.RPP', the final file will be:")
        print(f"[render]   {config.OUTPUT_DIR}/s01e06.{config.CODEC}")
        print(f"[render]")
        print(f"[render] REQUIRED REAPER CONFIGURATION:")
        print(f"[render]   1. File > Render...")
        print(f"[render]   2. Source: Master mix")
        print(f"[render]   3. Bounds: Entire project")
        print(f"[render]   4. Sample rate: {config.SAMPLE_RATE} Hz")
        print(f"[render]   5. Format: {config.CODEC.upper()}, {config.BIT_DEPTH} bit")
        print(f"[render]   6. Output: Directory + $project")
        print(f"[render]   7. Save as preset (optional)")
        sys.exit(1)
    
    output_dir = Path(sys.argv[1])
    
    # Create directory if it doesn't exist
    output_dir.mkdir(parents=True, exist_ok=True)
    
    print(f"[render] Sherlock Audio Pipeline - Render Mix")
    print(f"[render]")
    print(f"[render] Ensure Reaper is open with the project loaded")
    print(f"[render]")
    
    render_mix(output_dir)
